# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-kinoite-f43
description: Optimized Kinoite 43 with Fresh, Tilix, and VM drivers.

# Switched to Kinoite (KDE) for Fedora 43
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      # Tilix is usually in the main repos, but we'll ensure starship stays
      copr:
        - atim/starship
    install:
      # VMware Smooth Performance Drivers
      - open-vm-tools
      - open-vm-tools-desktop
      # Your Core Tools
      - tilix
      - micro
      - starship
      - git
      - curl
    remove:
      # Swapping pre-installed Firefox for Flatpak version
      - firefox
      - firefox-langpacks

  - type: script
    scripts:
      # Custom script to grab the 'Fresh' binary since it's rarely in RPM repos
      - install-fresh.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.kde.kdenlive # Example: KDE video editor
      - scope: user

  - type: signing
  
