# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kinoite-vmware-f43
description: Optimized Kinoite 43 with Fresh, Tilix, and VM drivers.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: "43" 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-43/atim-starship-fedora-43.repo
    install:
      - open-vm-tools
      - open-vm-tools-desktop
      - tilix
      - micro
      - starship
      - git
      - curl
      - zsh
      - ulauncher # Add this
      - wmctrl    # Helpful for Ulauncher window-switching extensions
  - type: signing # This tells BlueBuild to sign the final image
